# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.box_version = "2.0"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
    config.vm.provision :file do |file|
      file.source      = 'post_setup.sh'
      file.destination = '/home/vagrant/post_setup.sh'
    end
    config.vm.provision :shell, path: "setup.sh"

end